name: Publish ua-parser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions: {}

env:
  ENVNAME: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
      url: https://${{ github.event_name != 'release' && 'test.' || '' }}pypi.org/p/ua-parser

    permissions:
      id-token: write

    steps:
    - name: Checkout working copy
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: "3.x"
    - name: Install dependency
      run: |
        python -mpip install --upgrade pip
        python -mpip install build
    - name: Build sdist and wheel
      run: python -mbuild
    - name: Publish to testpypi
      if: ${{ env.ENVNAME == 'testpypi' }}
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verbose: true
    - name: Publish to pypi
      if: ${{ env.ENVNAME == 'pypi' }}
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # v1.14.2
      with:
        verbose: true
